name: Issue Close Require

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  issue-close-require:
    runs-on: ubuntu-latest
    steps:
      - name: needs more info
        uses: actions-cool/issues-helper@v2
        with:
          actions: 'close-issues'
          labels: 'Needs more info'
          inactive-day: 3
          body: |
            Since the issue was labeled with `Needs more info`, but no response in 3 days. This issue will be closed. If you have any questions, you can comment and reply.
            由于该 issue 被标记为需要更多信息，却 3 天未收到回应。现关闭 issue，若有任何问题，可评论回复。
