name: 'publish @waline/vercel'

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/release-server.yml
      - packages/server/**

permissions:
  contents: write
  id-token: write

jobs:
  npm:
    runs-on: ubuntu-latest
    outputs:
      old-version: ${{ steps.publish-server.outputs.old-version }}
      version: ${{ steps.publish-server.outputs.version }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  
    - uses: pnpm/action-setup@v2
    - uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: pnpm
    - run: pnpm install --frozen-lockfile
      
    - id: publish-server
      name: "publish @waline/vercel"
      uses: JS-DevTools/npm-publish@v2
      with:
        token: ${{ secrets.NPM_TOKEN }}
        package: ./packages/server

  docker:
    needs: npm
    if: ${{ needs.npm.outputs.old-version != needs.npm.outputs.version || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push alpine
      uses: docker/build-push-action@v4
      with:
        file: ./packages/server/Dockerfile.alpine
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        push: true
        tags: |
          lizheming/waline:alpine
          lizheming/waline:${{ needs.npm.outputs.version }}-alpine

    - name: Build and push debian
      uses: docker/build-push-action@v4
      with:
        file: ./packages/server/Dockerfile
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        push: true
        tags: |
          lizheming/waline:latest
          lizheming/waline:${{ needs.npm.outputs.version }}
